# Generated by Django 2.2 on 2019-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190614_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
        migrations.AlterField(
            model_name='address',
            name='addressee',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(max_length=50),
        ),
    ]
