# Generated by Django 2.2 on 2019-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190614_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['addressee'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='grocerystore',
            options={'ordering': ['name'], 'verbose_name_plural': 'Grocery Stores'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['store'], 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='address',
            name='is_Store',
            field=models.BooleanField(default=False),
        ),
    ]
