# Generated by Django 2.2 on 2019-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20190614_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_Store',
            field=models.BooleanField(),
        ),
    ]
