# Generated by Django 2.2 on 2019-06-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190614_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_Store',
            new_name='Store',
        ),
    ]
