# Generated by Django 2.2 on 2019-06-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20190614_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Store',
            new_name='Store_A_Bombastic',
        ),
    ]
