# Generated by Django 2.2 on 2019-06-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20190614_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='suite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
